# Generated by Django 4.0.3 on 2022-06-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
