# Generated by Django 4.0.3 on 2022-06-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_sale_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
