# Generated by Django 4.0.4 on 2022-06-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='house',
        ),
    ]
