# Generated by Django 4.0.4 on 2022-06-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_cartitem_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='thickness',
            field=models.PositiveSmallIntegerField(choices=[('Традиционное', 'Традиционное'), ('Тонкое', 'Тонкое')], max_length=30, null=True),
        ),
    ]
