# Generated by Django 4.0.4 on 2022-06-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_cartitem_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('1', 'Маленькая'), ('2', 'Средняя'), ('3', 'Большая')], max_length=30, null=True),
        ),
    ]
