# Generated by Django 4.0.4 on 2022-06-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('Маленькая', 'Маленькая'), ('Средняя', 'Средняя'), ('Большая', 'Большая')], max_length=30, null=True),
        ),
    ]
