# Generated by Django 4.0.3 on 2022-06-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_customer_orderproduct_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='customer',
        ),
    ]
