# Generated by Django 4.0.3 on 2022-06-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_name_order_address_remove_order_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, choices=[('Маленькая', 'Маленькая'), ('Средняя', 'Средняя'), ('Большая', 'Большая')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='thickness',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Традиционное'), (2, 'Тонкое')], null=True),
        ),
    ]
