# Generated by Django 4.0.4 on 2022-06-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_cartitem_size_alter_cartitem_thickness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='name',
        ),
    ]
