# Generated by Django 4.0.4 on 2022-06-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_orderproduct_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='customer',
        ),
    ]
