# Generated by Django 4.0.4 on 2022-06-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_orderproduct_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='adress',
        ),
    ]
